"""
Regenerate guile/_lucide_data.py from a lucide-static npm tarball.

Lucide ships one .svg file per icon. We do not want ~2000 separate files or
the repeated ``<svg …>`` wrapper in the package, so this script extracts just
the inner markup (the <path>/<circle>/… children) of every icon and writes a
single ``{name: inner_svg}`` dict. gui.icon() re-wraps that inner markup in a
standard <svg> shell at call time.

Usage:
    python tools/gen_lucide.py                 # downloads the latest tarball
    python tools/gen_lucide.py path/to.tgz     # uses a local tarball

The icons are Lucide (ISC License); a subset derives from Feather (MIT). The
full attribution is written into the header of the generated module and lives
in LICENSE at the repo root.
"""
import io
import os
import re
import sys
import json
import tarfile
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "guile", "_lucide_data.py")
REGISTRY = "https://registry.npmjs.org/lucide-static"

_INNER = re.compile(r"<svg[^>]*>(.*?)</svg>", re.S)
_COMMENT = re.compile(r"<!--.*?-->", re.S)
_BETWEEN = re.compile(r">\s+<")
_WS = re.compile(r"\s+")


def _fetch_latest_tarball() -> bytes:
    with urllib.request.urlopen(REGISTRY) as r:
        meta = json.loads(r.read().decode("utf-8"))
    version = meta["dist-tags"]["latest"]
    url = meta["versions"][version]["dist"]["tarball"]
    print(f"lucide-static latest = {version}\ndownloading {url}")
    with urllib.request.urlopen(url) as r:
        return r.read()


def _clean(raw: str) -> str:
    raw = _COMMENT.sub("", raw)
    inner = _INNER.search(raw).group(1)
    inner = _BETWEEN.sub("><", inner).strip()
    inner = _WS.sub(" ", inner)
    return inner


def main() -> None:
    if len(sys.argv) > 1:
        blob = open(sys.argv[1], "rb").read()
    else:
        blob = _fetch_latest_tarball()

    tar = tarfile.open(fileobj=io.BytesIO(blob))
    version = json.loads(tar.extractfile("package/package.json").read())["version"]

    icons = {}
    for m in tar.getmembers():
        if m.name.endswith(".svg") and "/icons/" in m.name:
            name = os.path.basename(m.name)[:-4]
            icons[name] = _clean(tar.extractfile(m).read().decode("utf-8"))
    icons = dict(sorted(icons.items()))

    lines = [
        '"""',
        "Vendored Lucide icon path data — DO NOT EDIT BY HAND.",
        f"Generated by tools/gen_lucide.py from lucide-static v{version}.",
        "",
        "Lucide (https://lucide.dev) is under the ISC License; a subset of icons",
        "derives from Feather (MIT). Full license text is in LICENSE at the repo",
        "root. Each value is the inner SVG markup; gui.icon() adds the <svg> shell.",
        '"""',
        f'LUCIDE_VERSION = "{version}"',
        "",
        "ICONS = {",
    ]
    for name, inner in icons.items():
        lines.append(f"    {name!r}: {inner!r},")
    lines.append("}")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    size = os.path.getsize(OUT)
    print(f"wrote {os.path.normpath(OUT)}: {len(icons)} icons, {size // 1024} KB")


if __name__ == "__main__":
    main()
